### ISSUE TITLE
Add format as you type feature

### ISSUE THREAD

**Issue by emri99** [cedvdb/phone_form_field#10]
Do you plan to add a format as you type feature ?

I would be pleased to help achieving this functionality however I don't find helpful data in your other metadata package to get easy information for this.

**Comment by cedvdb** [comment]
I added the metadata to `phone_number_metadata: 2.1.0`

I do not have the time to test that everything is okay right now though

**Comment by emri99** [comment]
Thanks for you reactivity. I’ll do my best to create issues/PR we were
talking about yesterday and to take a look at those latest changes.
My weekend being a little busy, I cannot ensure that all will be done by
tomorrow ;)

**Comment by emri99** [comment]
Hello,
Sorry for late news, some unforeseen family health events prevent me for
being as effective as I expected.

That said, I have take a look deeper about your latest commits & changes
and I've got some misunderstandings about how should I proceed :

   - main branch has only 4 commits and no other history
   - dev branch is 68 commits ahead and 4 behind main branch, so I'm a bit
   confused on the workflow you're using.

Check https://github.com/cedvdb/phone_form_field/network for a visual
representation of what I'm trying to say ;)

Can you please tell me what's your expectations for contributions ?
Thanks.

**Comment by cedvdb** [comment]
Some weeks ago, I used this repository as a git submodule and also as a sub tree. I was not that familiar with the process of those 2 things and I twisted the git history somehow. 

Since at that point in time no one except me seemed I took less care about the git history etc and did not think much of it.

Anyway, to proceed forward I got to make sure that does not happen again and clean the history. However I've a lot on my plate currently so what I did is rename the current dev to `dev_legacy` and copied `main` onto a new `dev` branch. This allows for a clean state to go forward, I do not have the time currently to fix the old history.

--------------------------------------

The package I believe the formatting contribution needs to happen is in the repository phone_numbers_parser, the history is clean over there https://github.com/cedvdb/phone_numbers_parser/tree/dev

**Comment by emri99** [comment]
The parsing should take place in the parser repo, but I think the input formatter may be defined here ;)

**Comment by cedvdb** [comment]
So, Formats are different by region. Therefor if the phone_numbers_parsers is used, that would be confusing for the end user. 

Another option would be to use expose `BasePhoneFormField`  which has no dependency on a phone parser and let the user do all the manual work: (validation, formatting, ...), which was the idea behind this class.

**Comment by cedvdb** [comment]
I'm making some naive progress on this, I'll probably have something by tomorrow.

**Comment by cedvdb** [comment]
This is now added to the underlying library. There is now a `PhoneNumberFormatter` that can be used in v3.0.0 of https://pub.dev/packages/phone_numbers_parser

There is a breaking change where any insteance of `dialCode` was renamed `countryCode` as dial code was semantically incorrect.

So this is now easily doable.
